version: "3.9"

services:
  api:
    image: ${DOCKER_REGISTRY-}purewebapi
    build:
      context: .
      dockerfile: src/Pure.WebApi/Dockerfile
    environment:
      - PURE_DB=Host=postgres;Database=PureWebApi;Username=postgres;Password=admin
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=onlyForDev
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres
    ports:
      - "5000:80"
      - "5001:443"
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4
    depends_on:
      - postgres
    ports:
      - "8080:8080"